AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VpcCidrBlock:
    Type: String
  VpcDomain:
    Type: String
  AzOne:
    Type: String
  AzTwo:
    Type: String
  SubnetPublicOneCidr:
    Type: String
  SubnetPublicTwoCidr:
    Type: String
  SubnetPrivateOneCidr:
    Type: String
  SubnetPrivateTwoCidr:
    Type: String
Resources:
  Bucket:
    Type: Custom::Value
    Properties:
      ServiceToken: !ImportValue cfn-lambda-value:LambdaArn
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - !ImportValue cfn-template-s3:DomainName
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${Bucket}/piece/vpc/vpc.yaml'
      Parameters:
        CidrBlock: !Ref VpcCidrBlock
        VpcDomain: !Ref VpcDomain
  PublicSubnetOne:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${Bucket}/piece/subnet/subnet_public.yaml'
      Parameters:
        CidrBlock: !Ref SubnetPublicOneCidr
        AvailablityZone: !Ref AzOne
        VpcResourceId: !GetAtt Vpc.Outputs.OutputResourceId
        VpcInternetGateway: !GetAtt Vpc.Outputs.OutputInternetGateway
  PublicSubnetOneNat:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${Bucket}/piece/nat/nat.yaml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetOne.Outputs.OutputSubnet
  PublicSubnetTwo:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${Bucket}/piece/subnet/subnet_public.yaml'
      Parameters:
        CidrBlock: !Ref SubnetPublicTwoCidr
        AvailablityZone: !Ref AzTwo
        VpcResourceId: !GetAtt Vpc.Outputs.OutputResourceId
        VpcInternetGateway: !GetAtt Vpc.Outputs.OutputInternetGateway
  PublicSubnetTwoNat:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${Bucket}/piece/nat/nat.yaml'
      Parameters:
        SubnetId: !GetAtt PublicSubnetTwo.Outputs.OutputSubnet
  PrivateSubnetOne:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${Bucket}/piece/subnet/subnet_private.yaml'
      Parameters:
        CidrBlock: !Ref SubnetPrivateOneCidr
        AvailablityZone: !Ref AzOne
        VpcResourceId: !GetAtt Vpc.Outputs.OutputResourceId
        NatGateway: !GetAtt PublicSubnetOneNat.Outputs.OutputNatGateway
  PrivateSubnetTwo:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${Bucket}/piece/subnet/subnet_private.yaml'
      Parameters:
        CidrBlock: !Ref SubnetPrivateTwoCidr
        AvailablityZone: !Ref AzTwo
        VpcResourceId: !GetAtt Vpc.Outputs.OutputResourceId
        NatGateway: !GetAtt PublicSubnetTwoNat.Outputs.OutputNatGateway
