AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CidrBlock:
    Type: String
    Description: "x.x.x.x/x"
  VpcDomain:
    Type: String
    Description: "vpc.local"
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref CidrBlock
      Tags:
        - Key: Name
          Value: !Ref CidrBlock
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref VpcDomain
      VPCs:
        - VPCId: !Ref Vpc
          VPCRegion: !Ref AWS::Region
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
      - Key: Name
        Value: !Ref CidrBlock
  VpcGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway
Outputs:
  OutputResourceId:
    Value: !Ref Vpc
    Export:
      Name: !Sub ${AWS::StackName}:ResourceId
  OutputCidrBlock:
    Value: !GetAtt Vpc.CidrBlock
    Export:
      Name: !Sub ${AWS::StackName}:CidrBlock
  OutputZoneId:
    Value: !Ref HostedZone
    Export:
      Name: !Sub ${AWS::StackName}:HostedZoneId
  OutputZoneName:
    Value: !Ref VpcDomain
    Export:
      Name: !Sub ${AWS::StackName}:HostedZoneName
  OutputInternetGateway:
    Value: !Ref InternetGateway
    Export:
      Name: !Sub ${AWS::StackName}:InternetGateway
  OutputVpcGatewayAttachment:
    Value: !Ref VpcGatewayAttachment
    Export:
      Name: !Sub ${AWS::StackName}:VpcGatewayAttachment
