AWSTemplateFormatVersion: 2010-09-09
Resources:
  Bucket:
    Type: Custom::Value
    Properties:
      ServiceToken: !ImportValue cfn-lambda-value:LambdaArn
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - !ImportValue cfn-template-s3:DomainName
  Vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${Bucket}/component/vpc/vpc-2az.yaml'
      Parameters:
        VpcCidrBlock: 10.1.0.0/16
        VpcDomain: vpc.local
        AzOne: !Select [0, !GetAZs '']
        AzTwo: !Select [1, !GetAZs '']
        SubnetPublicOneCidr: 10.1.10.0/24
        SubnetPublicTwoCidr: 10.1.20.0/24
        SubnetPrivateOneCidr: 10.1.11.0/24
        SubnetPrivateTwoCidr: 10.1.21.0/24
      TimeoutInMinutes: 60
