AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubnetId:
    Type: String
Resources:
  Eip:
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt Eip.AllocationId
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'
Outputs:
  OutputEip:
    Value: !Ref Eip
    Export:
      Name: !Sub '${AWS::StackName}:Eip'
  OutputNatGateway:
    Value: !Ref NatGateway
    Export:
      Name: !Sub '${AWS::StackName}:NatGateway'
